version: '3.1'
services:
  app:
    container_name: app-pichincha
    image: app-pichincha
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=neoris$2023
      - POSTGRES_USER=test
      - POSTGRES_DB=pichincha
